#
# https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/installation/linux/index.adoc#deb-installation-on-debian-or-ubuntu
#
description: Install the temurin JDK
steps:
  - run:
      name: Add wget, apt-transport-https, gnupg
      command: apt-get update && apt-get install -y --no-install-recommends wget apt-transport-https gpg ca-certificates
  - run:
      name: Add temurin GPG key
      command: wget -qO - "https://packages.adoptium.net/artifactory/api/gpg/key/public" | gpg --dearmor | tee /etc/apt/trusted.gpg.d/adoptium.gpg > /dev/null
  - run:
      name: Add temurin repo
      command: echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
  - run:
      name: Install temurin-25
      command: apt-get update && apt-get install -y --no-install-recommends temurin-25-jdk
