steps:
  - run:
      name: Install protobuf
      command: |
        curl -LO "https://github.com/protocolbuffers/protobuf/releases/download/v21.11/protoc-21.11-osx-universal_binary.zip"
        unzip protoc*.zip -d $HOME/.local
        echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
