when: << pipeline.parameters.run_promotion_backend_administration >>
jobs:
  - promote_server:
      context:
        - credentials-ehrenamtskarte
  - promote_github_release:
      platform: web
      context:
        - deliverino
      requires:
        - promote_server
