docker:
  - image: cimg/base:2022.09
parameters:
  production:
    description: Whether builds are delivered to production or beta.
    type: boolean
steps:
  - run:
      name: Install Curl
      command: |
        sudo apt update
        sudo apt install curl -y
  - attach_workspace:
      at: /tmp/workspace
  - add_ssh_keys:
      fingerprints:
        - "a1:3f:a7:c3:ff:12:40:1d:85:de:a7:ab:12:3f:cc:05"
  - when:
      condition:
        equal: [ true, << parameters.production >> ]
      steps:
        - run:
            name: SFTP upload package
            command: |
              echo "|1|iikuvSrIo3wkj+EqUgLRMsAq6yk=|r9bSjkawWFa94b45qE/se5Oio5k= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIED3MwobbCs+ENMLXdyqlJb3bJ26TuIYt977TA3NrN66" >> known_hosts
              echo "Uploading: " /tmp/workspace/debs/backend/*.deb
              sftp -b - -o UserKnownHostsFile=known_hosts ci@entitlementcard.tuerantuer.org:/local-apt-repository/ \<<< "put -r /tmp/workspace/debs/backend/*.deb"
        - run:
            name: Install package via webhook
            command: |
              curl https://webhook.entitlementcard.tuerantuer.org/hooks/install-backend-$EAK_WEBHOOK
  - when:
      condition:
        equal: [ false, << parameters.production >> ]
      steps:
        - run:
            name: SFTP upload package
            command: |
              echo "|1|dkYQrdGB1QML0o+POL3QzAkBbek=|b4Tm0Ymh82UKyZPJfVKy4t+MFV8= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIONuARu18Fktz+j4QosI+nRqgMnFOMgE7OZLuTOwgZ0k" >> known_hosts
              echo "Uploading: " /tmp/workspace/debs/backend/*.deb
              sftp -b - -o UserKnownHostsFile=known_hosts ci@entitlementcard-test.tuerantuer.org:/local-apt-repository/ \<<< "put -r /tmp/workspace/debs/backend/*.deb"
        - run:
            name: Install package via webhook
            command: |
              curl https://webhook.entitlementcard-test.tuerantuer.org/hooks/install-backend-$EAK_WEBHOOK        
