name: 'PR'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'administration/**'

jobs:
  administration-check:
    name: 'administration check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20.18.0'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install node modules
        run: npm ci --cache ~/.npm --prefer-offline

      - name: Check Typescript
        run: npm run ts:check
        working-directory: administration

      - name: Run Lint
        run: npm run lint
        working-directory: administration

      - name: Check circular dependencies
        run: npm run check-circular-deps
        working-directory: administration

      - uses: ArtiomTr/jest-coverage-report-action@v2
        name: Run tests with coverage
        with:
          base-coverage-file: report.json
          skip-step: install
          working-directory: administration
          test-script: npm run test:coverage -- --silent --ci --json --testLocationInResults --outputFile=report.json --maxWorkers=1
