name: 'PR'

on:
  pull_request:
    branches:
      - main
    paths:
      - .prettierrc
      - eslint.config-base.mjs
      - graphql.config.yml
      - package.json
      - package-lock.json
      - administration/**
      - build-configs/**

jobs:
  administration-check:
    name: 'administration check'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '20.18.0'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install node modules
        run: npm ci

      - name: Check Typescript
        run: npm run ts:check
        working-directory: administration

      - name: Run Lint
        run: npm run lint
        working-directory: administration

      - name: Check circular dependencies
        run: npm run check-circular-deps
        working-directory: administration

      - name: Run tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: github.event.pull_request.user.login != 'dependabot[bot]'
        with:
          base-coverage-file: report.json
          skip-step: install
          working-directory: administration
          test-script: npm run test:coverage -- --silent --ci --json --testLocationInResults --outputFile=report.json --maxWorkers=1

      - name: Run tests
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: npm run test -- --maxWorkers=1
        working-directory: administration
