name: df_build_config
description: Build your app config via code generation from .json files in a type safe way
version: 2.2.0-alpha.1
homepage: https://github.com/knaeckeKami/config_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_gen: ^1.0.0
  build: ^2.0.0

dev_dependencies:

